spring:
  profiles:
    active:
    - dev

---
server:
  port: 8002

spring:
  profiles: dev8002
  application:
    name: mssc-dept-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: accp
    dbcp2:
      min-idle: 5                                     #数据库连接池最小维持连接数
      initial-size: 5                                 #初始化连接数
      max-total: 5                                    #最大连接数
      max-wait-millis: 200    

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.jbit.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/,http://eureka3:7003/eureka/
  instance:
    instance-id: dept_server2
    prefer-ip-address: true
    
info:
  app.name: com.jbit
  company.name: whcm
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  toni.temp: 赵波


---
server:
  port: 8001

spring:
  profiles: dev8001
  application:
    name: mssc-dept-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: accp
    dbcp2:
      min-idle: 5                                     #数据库连接池最小维持连接数
      initial-size: 5                                 #初始化连接数
      max-total: 5                                    #最大连接数
      max-wait-millis: 200    

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.jbit.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/,http://eureka3:7003/eureka/
  instance:
    instance-id: dept_server1
    prefer-ip-address: true
    
info:
  app.name: com.jbit
  company.name: whcm
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  toni.temp: 赵波


---
server:
  port: 8003

spring:
  profiles: dev8003
  application:
    name: mssc-dept-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB03?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: accp
    dbcp2:
      min-idle: 5                                     #数据库连接池最小维持连接数
      initial-size: 5                                 #初始化连接数
      max-total: 5                                    #最大连接数
      max-wait-millis: 200    

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.jbit.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/,http://eureka3:7003/eureka/
  instance:
    instance-id: dept_server3
    prefer-ip-address: true
    
info:
  app.name: com.jbit
  company.name: whcm
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  toni.temp: 赵波